repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: mixed-line-ending
        args: [ --fix=lf ]
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.286"
    hooks:
      - id: ruff

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        language: system
        entry: bash -c 'cd sink && exec cargo fmt'
        types: [rust]
        files: ^sink/

  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        language: system
        entry: bash -c 'cd sink && exec cargo clippy -- -Dclippy::all -Dclippy::pedantic -Dclippy::cargo -Aclippy::cargo_common_metadata'
        types: [rust]
        files: ^sink/
