version: "3.9"

services:
  vent:
    build:
      context: ./vent
    restart: always
    tty: true
    environment:
      VENT_ADDRESS: "tcp://*:5559"

  task:
    build:
      context: ./task
    restart: always
    tty: true
    depends_on:
      - vent
      - sink
    environment:
      VENT_ADDRESS: "tcp://vent:5559"
      SINK_ADDRESS: "tcp://sink:5559"
      SUB_FILTER: ""

  sink:
    build:
      context: ./sink
    restart: always
    tty: true
    environment:
      SINK_ADDRESS: "tcp://*:5559"
