name: Vent Lint and Test

on:
  push:
    - "sink/**"
  pull_request:
    - "sink/**"


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true


jobs:
  vent:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # 3.6.0

      - name: Setup PDM
        uses: pdm-project/setup-pdm@ddc33ca746b5716353581f988b29464200212702  # 3.3.0
        with:
          python-version: "3.11"
          cache: true

      - name: Install dependencies
        run: |
          cd vent
          pdm install --dev

      - name: Run pre-commit
        run: |
          cd vent
          pdm install --dev

      - name: Run tests
        run: |
          cd vent
          pdm test
